version: "3"
services:
  test.mysql:
    container_name: test.mysql
    image: mysql:8.0.32
    command: --authentication_policy=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${TEST_DB_PASSWORD}
      MYSQL_USER: ${TEST_DB_USER}
      MYSQL_PASSWORD: ${TEST_DB_PASSWORD}
      MYSQL_DATABASE: ${TEST_DB_NAME}
      TZ: Asia/Seoul
    volumes:
      - test_mysql_db:/var/lib/mysql
    ports:
      - ${TEST_DB_PORT}:3306
    expose:
      - ${TEST_DB_PORT}

volumes:
  test_mysql_db:
